import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function _404() {
  return (
    <div className={styles.container}>
      <Head>
        <title>tr1e_</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div> LOLOLOL</div>
    </div>
  );
}
